<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>LiethOrganigrammeAssistant</AssemblyName>
    <RootNamespace>LiethOrganigrammeAssistant</RootNamespace>
    <Version>1.0.1</Version>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <FileVersion>1.0.1.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Updater\**" />
    <EmbeddedResource Include="Assets\lieth-organigramme-logo.png" LogicalName="LiethOrganigrammeAssistant.Assets.lieth-organigramme-logo.png" />
    <EmbeddedResource Include="Assets\arsef-logo.jpeg" LogicalName="LiethOrganigrammeAssistant.Assets.arsef-logo.jpeg" />
  </ItemGroup>
</Project>
